steps:
  # Step 1: Fetch The Trigger Branch
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        echo "Fetching all branches..."
        git fetch origin
        echo "Checking out branch: ${BRANCH_NAME}"
        git checkout ${BRANCH_NAME}
  # Step 3: Install Poetry & Build The App
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --upgrade pip
        pip install poetry
        python3 --version
        pip --version
        poetry --version
        python3 -m venv venv
        source venv/bin/activate
        poetry install
    id: 'Install Poetry'
  # Step 4: Install latest version of endorctl
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        curl https://api.endorlabs.com/download/latest/endorctl_linux_amd64 -o endorctl
        echo "$(curl -s https://api.endorlabs.com/sha/latest/endorctl_linux_amd64)  endorctl" | sha256sum -c
        chmod +x ./endorctl
        ./endorctl --version
    id: 'Install latest version of endorctl'
  # Step 5: SCA Scan With EndorLabs
  - name: 'python'
    entrypoint: 'bash'
    args: ["-c", "./endorctl scan --namespace=$$NAMESPACE --api-key=$$ENDOR_API_CREDENTIALS_KEY --api-secret=$$ENDOR_API_CREDENTIALS_SECRET --pr --pr-baseline=$$BASELINE_BRANCH --pr-incremental"]
    secretEnv: ['ENDOR_API_CREDENTIALS_KEY', 'ENDOR_API_CREDENTIALS_SECRET']
    env:
      - 'NAMESPACE=ananth-learn'
      - 'BASELINE_BRANCH=master'
    id: 'SCA Scan With EndorLabs'

availableSecrets:
  secretManager:
  - versionName: projects/1062646801031/secrets/endor-api-key/versions/1
    env: 'ENDOR_API_CREDENTIALS_KEY'
  - versionName: projects/1062646801031/secrets/endor-api-secret/versions/1
    env: 'ENDOR_API_CREDENTIALS_SECRET'

options:
  logging: 'CLOUD_LOGGING_ONLY'
